repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/python/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
